php:
  build: "./docker/php"
  volumes:
   - ".:/var/www"
   - "./docker/php/init.sh:/init.sh"
  links:
   - sql
  environment:
    - COMPOSER_MEMORY_LIMIT=-1

web:
  image: khromov/alpine-nginx-php8
  ports:
   - "80:8080"
   - "8000:8080"
  volumes:
     - ".:/var/www"
     - "./docker/nginx/main.conf:/etc/nginx/nginx.conf"
  links:
   - php

sql:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: 'flashcards'
    MYSQL_USER: 'user'
    MYSQL_PASSWORD: 'password'
    MYSQL_ROOT_PASSWORD: 'password'
  ports:
    - '3306:3306'
  expose:
    - '3306'

